//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOTA_2_GPM_Overlay___Main.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DOTA_2_GPM_Overlay___Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Alchemist_icon {
            get {
                object obj = ResourceManager.GetObject("Alchemist_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Alchemist_icon1 {
            get {
                object obj = ResourceManager.GetObject("Alchemist_icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dota 2 GPM Overlay.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTA 2 GPM Overlay is still running.
        /// </summary>
        internal static string BalloonTipText {
            get {
                return ResourceManager.GetString("BalloonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTA 2 GPM Overlay.
        /// </summary>
        internal static string BalloonTipTitle {
            get {
                return ResourceManager.GetString("BalloonTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dota 2 is not running. Please start Dota 2..
        /// </summary>
        internal static string Dota2NotRunning {
            get {
                return ResourceManager.GetString("Dota2NotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dota2.
        /// </summary>
        internal static string Dota2ProcessName {
            get {
                return ResourceManager.GetString("Dota2ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameStateListener could not start. Try running this program as Administrator. Exiting..
        /// </summary>
        internal static string ListenerCannotStart {
            get {
                return ResourceManager.GetString("ListenerCannotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.opendota.com/api.
        /// </summary>
        internal static string OpenDotaAPIBaseURL {
            get {
                return ResourceManager.GetString("OpenDotaAPIBaseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to benchmarks.
        /// </summary>
        internal static string OpenDotaAPIBenchmarkMethod {
            get {
                return ResourceManager.GetString("OpenDotaAPIBenchmarkMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hero_id.
        /// </summary>
        internal static string OpenDotaAPIHeroIdParam {
            get {
                return ResourceManager.GetString("OpenDotaAPIHeroIdParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry key for steam not found, cannot create Gamestate Integration file..
        /// </summary>
        internal static string SteamRegistryKeyNotFound {
            get {
                return ResourceManager.GetString("SteamRegistryKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occured. Exiting..
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Void_Chibi {
            get {
                object obj = ResourceManager.GetObject("Void_Chibi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
